# ARG DEBIAN_FRONTEND=noninteractive
# ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
# From ubuntu:18.04 as ffnc
From ubuntu:noble as ffnc
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /
COPY ./deploy/sources_noble.list /etc/apt/sources.list
RUN apt-get update; exit 0
RUN apt-get install -y curl gcc g++ libssl-dev openssl pkg-config make cmake 
#  autoconf pkg-config 

WORKDIR /app
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN /bin/bash -c "source '$HOME/.cargo/env'"
# COPY ./deploy/config-global /root/.cargo/config

COPY ./src ./src
COPY ./static ./static
COPY ./Cargo.toml .
COPY ./Cargo.lock .
COPY ./log4rs.yaml .
COPY ./.env .
COPY ./log ./log


RUN /root/.cargo/bin/cargo build --release --features log,es
RUN cp /app/target/release/webtalk /app/webtalk
# RUN rm -rf target src Cargo.toml

EXPOSE 9004 9002
EXPOSE 9003/udp 9011/udp

CMD ["/app/webtalk"]